=== nicolasochem/tzip/proposals/tzip-16/metadata-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "#/definitions/contract-metadata-tzip-16",
  "definitions": {
    "bignum": {
      "title": "Big number",
      "description": "Decimal representation of a big number",
      "type": "string"
    },
    "contract-metadata-tzip-16": {
      "title": "contract-metadata-tzip-16",
      "description": "Smart Contract Metadata Standard (TZIP-16).",
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "license": {
          "oneOf": [
            {
              "title": "License-name",
              "type": "string"
            },
            {
              "title": "License-object",
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "details": {
                  "type": "string"
                }
              },
              "required": [
                "name"
              ],
              "additionalProperties": false
            }
          ]
        },
        "authors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "interfaces": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "views": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "description": {
                "type": "string"
              },
              "implementations": {
                "type": "array",
                "items": {
                  "oneOf": [
                    {
                      "title": "michelson-storage-view",
                      "type": "object",
                      "properties": {
                        "parameter": {
                          "$ref": "#/definitions/micheline.tzip-16.expression"
                        },
                        "return-type": {
                          "$ref": "#/definitions/micheline.tzip-16.expression"
                        },
                        "code": {
                          "$ref": "#/definitions/micheline.tzip-16.expression"
                        },
                        "annotations": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "name": {
                                "type": "string"
                              },
                              "description": {
                                "type": "string"
                              }
                            },
                            "required": [
                              "description",
                              "name"
                            ],
                            "additionalProperties": false
                          }
                        },
                        "version": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "code"
                      ],
                      "additionalProperties": false
                    },
                    {
                      "title": "rest-api-query-view",
                      "type": "object",
                      "properties": {
                        "specification-uri": {
                          "type": "string"
                        },
                        "base-uri": {
                          "type": "string"
                        },
                        "path": {
                          "type": "string"
                        },
                        "method": {
                          "type": "string",
                          "enum": [
                            "GET",
                            "POST"
                          ]
                        }
                      },
                      "required": [
                        "path",
                        "specification-uri"
                      ],
                      "additionalProperties": false
                    }
                  ]
                }
              }
            },
            "required": [
              "implementations",
              "name"
            ],
            "additionalProperties": false
          }
        }
      },
      "additionalProperties": false
    },
    "micheline.tzip-16.expression": {
      "oneOf": [
        {
          "title": "Int",
          "type": "object",
          "properties": {
            "int": {
              "$ref": "#/definitions/bignum"
            }
          },
          "required": [
            "int"
          ],
          "additionalProperties": false
        },
        {
          "title": "String",
          "type": "object",
          "properties": {
            "string": {
              "$ref": "#/definitions/unistring"
            }
          },
          "required": [
            "string"
          ],
          "additionalProperties": false
        },
        {
          "title": "Bytes",
          "type": "object",
          "properties": {
            "bytes": {
              "type": "string",
              "pattern": "^[a-zA-Z0-9]+$"
            }
          },
          "required": [
            "bytes"
          ],
          "additionalProperties": false
        },
        {
          "title": "Sequence",
          "type": "array",
          "items": {
            "$ref": "#/definitions/micheline.tzip-16.expression"
          }
        },
        {
          "title": "Generic prim (any number of args with or without annot)",
          "type": "object",
          "properties": {
            "prim": {
              "$ref": "#/definitions/unistring"
            },
            "args": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/micheline.tzip-16.expression"
              }
            },
            "annots": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "required": [
            "prim"
          ],
          "additionalProperties": false
        }
      ]
    },
    "unistring": {
      "title": "Universal string representation",
      "description": "Either a plain UTF8 string, or a sequence of bytes for strings that contain invalid byte sequences.",
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "object",
          "properties": {
            "invalid_utf8_string": {
              "type": "array",
              "items": {
                "type": "integer",
                "minimum": 0,
                "maximum": 255
              }
            }
          },
          "required": [
            "invalid_utf8_string"
          ],
          "additionalProperties": false
        }
      ]
    }
  }
}

=== nicolasochem/tzip/proposals/tzip-16/examples/example-004.json
{
  "version": "0.42.0",
  "license": {
    "name": "MIT",
    "details": "The MIT License"
  },
  "interfaces": [
    "TZIP-16",
    "TZIP-12"
  ],
  "views": [
    {
      "name": "view0",
      "implementations": [
        {
          "code": []
        },
        {
          "specification-uri": "https://example.com/v1.json",
          "path": "/get-something"
        }
      ]
    }
  ]
}

=== nicolasochem/tzip/proposals/tzip-16/examples/example-005.json
{
  "version": "0.42.0",
  "license": {
    "name": "MIT",
    "details": "The MIT License"
  },
  "interfaces": [
    "TZIP-16",
    "TZIP-12"
  ],
  "views": [
    {
      "name": "view0",
      "implementations": [
        {
          "code": []
        },
        {
          "specification-uri": "https://example.com/v1.json",
          "path": "/get-something"
        }
      ]
    },
    {
      "name": "view-01",
      "implementations": [
        {
          "parameter": {
            "prim": "pair",
            "args": [
              {
                "prim": "mutez",
                "annots": [
                  "%amount"
                ]
              },
              {
                "prim": "string",
                "annots": [
                  "%name"
                ]
              }
            ]
          },
          "return-type": {
            "prim": "map",
            "args": [
              {
                "prim": "string"
              },
              {
                "prim": "string"
              }
            ]
          },
          "code": [
            {
              "prim": "DUP"
            },
            {
              "prim": "DIP",
              "args": [
                [
                  {
                    "prim": "CDR"
                  },
                  {
                    "prim": "PUSH",
                    "args": [
                      {
                        "prim": "string"
                      },
                      {
                        "string": "Huh"
                      }
                    ]
                  },
                  {
                    "prim": "FAILWITH"
                  }
                ]
              ]
            }
          ],
          "annotations": [
            {
              "name": "%amount",
              "description": "The amount which should mean something in context. It's in `mutez` which should also mean something more than lorem ipsum dolor whatever …"
            },
            {
              "name": "%name",
              "description": "The name of the thing being queried."
            }
          ],
          "version": "PsCARTHAGazKbHtnKfLzQg3kms52kSRpgnDY982a9oYsSXRLQEb"
        }
      ]
    }
  ]
}
